name: Build releases
on:
  push:
    tags:
      - '*'
jobs:
  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install Dependencies
        run: brew install xerces-c jack liblo libsndfile eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl libsoundio
      - name: Running cmake
        env:
          APPLE_CERT: "Apple Development: Tobias Hegemann (Tobias Hegemann)"
          CMAKE_BUILD_TYPE: Release
        run: 'cmake -DCMAKE_BUILD_TYPE=Release -DAPPLE_CERT="Apple Development: Tobias Hegemann (Tobias Hegemann)"" .'
      - name: Building
        run: make
      - name: Bundling
        run: make install
      - name: Publishing
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: DigitalStage_artefacts/Release/DigitalStage.app
          tag: "Release"
          overwrite: true

