name: Build nighly for macOS
on:
  push:
    branches: [ main, development ]
jobs:
  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MAOS_CERTIFICATE_PWD }}
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install Dependencies
        run: brew install xerces-c jack liblo libsndfile eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl libsoundio
      - name: Running cmake
        env:
          APPLE_CERT: "Apple Development: Tobias Hegemann (X3FUCE928U)"
          CMAKE_BUILD_TYPE: Release
        run: 'cmake -DCMAKE_BUILD_TYPE=Release -DAPPLE_CERT="Apple Development: Tobias Hegemann (X3FUCE928U)" .'
      - name: Building
        run: make
      - name: Create macOS App Bundle and wrapping it with DMG
        run: cpack -G DragNDrop
      - name: Publishing
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: InstallDigitalStage*.dmg
          tag: "Nightly"
          body: "Fresh midnight build, experimental, unstable, but an future insight. Please use macOS 10.5+ and don't forget to install jack audio: https://jackaudio.org/downloads/"
          prerelease: true
          overwrite: true
          file_glob: true

